#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 7.1
#  in conjunction with Tcl version 8.6
#    Apr 07, 2022 02:20:41 PM -03  platform: Windows NT

import sys
import tkinter as tk
import tkinter.ttk as ttk
from tkinter.constants import *

import sp31_support

class Toplevel1:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'

        top.geometry("698x480+315+70")
        top.minsize(120, 1)
        top.maxsize(1370, 749)
        top.resizable(1,  1)
        top.title("Toplevel 0")
        top.configure(background="#d9d9d9")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="black")

        self.top = top

        self.Button1 = tk.Button(self.top)
        self.Button1.place(relx=0.567, rely=0.738, height=34, width=257)
        self.Button1.configure(activebackground="#ececec")
        self.Button1.configure(activeforeground="#000000")
        self.Button1.configure(background="#d9d9d9")
        self.Button1.configure(command=sp31_support.jailbreak_newer)
        self.Button1.configure(compound='left')
        self.Button1.configure(disabledforeground="#a3a3a3")
        self.Button1.configure(font="-family {Segoe UI} -size 12")
        self.Button1.configure(foreground="#000000")
        self.Button1.configure(highlightbackground="#d9d9d9")
        self.Button1.configure(highlightcolor="black")
        self.Button1.configure(pady="0")
        self.Button1.configure(text='''Jailbreak (Newer devices)''')

        self.Button1_1_1_1 = tk.Button(self.top)
        self.Button1_1_1_1.place(relx=0.029, rely=0.306, height=34, width=257)
        self.Button1_1_1_1.configure(activebackground="#ececec")
        self.Button1_1_1_1.configure(activeforeground="#000000")
        self.Button1_1_1_1.configure(background="#d9d9d9")
        self.Button1_1_1_1.configure(command=sp31_support.install_dolphin)
        self.Button1_1_1_1.configure(compound='left')
        self.Button1_1_1_1.configure(disabledforeground="#a3a3a3")
        self.Button1_1_1_1.configure(font="-family {Segoe UI} -size 12")
        self.Button1_1_1_1.configure(foreground="#000000")
        self.Button1_1_1_1.configure(highlightbackground="#d9d9d9")
        self.Button1_1_1_1.configure(highlightcolor="black")
        self.Button1_1_1_1.configure(pady="0")
        self.Button1_1_1_1.configure(text='''Install Dolphin Browser''')

        self.Label1 = tk.Label(self.top)
        self.Label1.place(relx=0.344, rely=0.021, height=27, width=196)
        self.Label1.configure(activebackground="#f9f9f9")
        self.Label1.configure(activeforeground="black")
        self.Label1.configure(anchor='w')
        self.Label1.configure(background="#d9d9d9")
        self.Label1.configure(compound='left')
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(font="-family {Segoe UI} -size 18")
        self.Label1.configure(foreground="#000000")
        self.Label1.configure(highlightbackground="#d9d9d9")
        self.Label1.configure(highlightcolor="black")
        self.Label1.configure(text='''Snowpois0n 3.2.3''')

        self.Button1_1 = tk.Button(self.top)
        self.Button1_1.place(relx=0.567, rely=0.821, height=34, width=257)
        self.Button1_1.configure(activebackground="#ececec")
        self.Button1_1.configure(activeforeground="#000000")
        self.Button1_1.configure(background="#d9d9d9")
        self.Button1_1.configure(command=sp31_support.jailbreak_older)
        self.Button1_1.configure(compound='left')
        self.Button1_1.configure(disabledforeground="#a3a3a3")
        self.Button1_1.configure(font="-family {Segoe UI} -size 12")
        self.Button1_1.configure(foreground="#000000")
        self.Button1_1.configure(highlightbackground="#d9d9d9")
        self.Button1_1.configure(highlightcolor="black")
        self.Button1_1.configure(pady="0")
        self.Button1_1.configure(text='''Jailbreak (Older devices)''')

        self.Label2 = tk.Label(self.top)
        self.Label2.place(relx=0.573, rely=0.373, height=171, width=248)
        self.Label2.configure(activebackground="#f9f9f9")
        self.Label2.configure(activeforeground="black")
        self.Label2.configure(anchor='w')
        self.Label2.configure(background="#d9d9d9")
        self.Label2.configure(compound='left')
        self.Label2.configure(disabledforeground="#a3a3a3")
        self.Label2.configure(font="-family {Segoe UI} -size 10")
        self.Label2.configure(foreground="#000000")
        self.Label2.configure(highlightbackground="#d9d9d9")
        self.Label2.configure(highlightcolor="black")
        self.Label2.configure(text='''Jailbreak Android devices from Android
4.2 (Jelly Bean) until Android 9.0 (Oreo)

Select "Jailbrek (Older devices)" if your
device is running Android 4.2 or older.

Otherwise, if your device is running
Android 4.4 or newer, select
"Jailbreak (Newer devices)"''')

        self.Label2_1 = tk.Label(self.top)
        self.Label2_1.place(relx=0.024, rely=0.194, height=40, width=264)
        self.Label2_1.configure(activebackground="#f9f9f9")
        self.Label2_1.configure(activeforeground="black")
        self.Label2_1.configure(anchor='w')
        self.Label2_1.configure(background="#d9d9d9")
        self.Label2_1.configure(compound='left')
        self.Label2_1.configure(disabledforeground="#a3a3a3")
        self.Label2_1.configure(font="-family {Segoe UI} -size 12")
        self.Label2_1.configure(foreground="#000000")
        self.Label2_1.configure(highlightbackground="#d9d9d9")
        self.Label2_1.configure(highlightcolor="black")
        self.Label2_1.configure(text='''Install Dolphin Web Browser for older
Android devices.''')

        self.Button2 = tk.Button(self.top)
        self.Button2.place(relx=0.027, rely=0.735, height=34, width=257)
        self.Button2.configure(activebackground="#ececec")
        self.Button2.configure(activeforeground="#000000")
        self.Button2.configure(background="#d9d9d9")
        self.Button2.configure(command=sp31_support.reboot_device)
        self.Button2.configure(compound='left')
        self.Button2.configure(disabledforeground="#a3a3a3")
        self.Button2.configure(font="-family {Segoe UI} -size 12")
        self.Button2.configure(foreground="#000000")
        self.Button2.configure(highlightbackground="#d9d9d9")
        self.Button2.configure(highlightcolor="black")
        self.Button2.configure(pady="0")
        self.Button2.configure(text='''Reboot device''')

        self.Button2_1_1 = tk.Button(self.top)
        self.Button2_1_1.place(relx=0.026, rely=0.823, height=34, width=257)
        self.Button2_1_1.configure(activebackground="#ececec")
        self.Button2_1_1.configure(activeforeground="#000000")
        self.Button2_1_1.configure(background="#d9d9d9")
        self.Button2_1_1.configure(command=sp31_support.reboot_recovery)
        self.Button2_1_1.configure(compound='left')
        self.Button2_1_1.configure(disabledforeground="#a3a3a3")
        self.Button2_1_1.configure(font="-family {Segoe UI} -size 12")
        self.Button2_1_1.configure(foreground="#000000")
        self.Button2_1_1.configure(highlightbackground="#d9d9d9")
        self.Button2_1_1.configure(highlightcolor="black")
        self.Button2_1_1.configure(pady="0")
        self.Button2_1_1.configure(text='''Reboot Recovery''')

        self.Label2_1_1 = tk.Label(self.top)
        self.Label2_1_1.place(relx=0.086, rely=0.675, height=18, width=176)
        self.Label2_1_1.configure(activebackground="#f9f9f9")
        self.Label2_1_1.configure(activeforeground="black")
        self.Label2_1_1.configure(anchor='w')
        self.Label2_1_1.configure(background="#d9d9d9")
        self.Label2_1_1.configure(compound='left')
        self.Label2_1_1.configure(disabledforeground="#a3a3a3")
        self.Label2_1_1.configure(font="-family {Segoe UI} -size 12")
        self.Label2_1_1.configure(foreground="#000000")
        self.Label2_1_1.configure(highlightbackground="#d9d9d9")
        self.Label2_1_1.configure(highlightcolor="black")
        self.Label2_1_1.configure(text='''Android Reboot Options''')

        self.Label3 = tk.Label(self.top)
        self.Label3.place(relx=0.272, rely=0.083, height=52, width=297)
        self.Label3.configure(activebackground="#f9f9f9")
        self.Label3.configure(activeforeground="black")
        self.Label3.configure(anchor='w')
        self.Label3.configure(background="#d9d9d9")
        self.Label3.configure(compound='left')
        self.Label3.configure(disabledforeground="#a3a3a3")
        self.Label3.configure(foreground="#000000")
        self.Label3.configure(highlightbackground="#d9d9d9")
        self.Label3.configure(highlightcolor="black")
        self.Label3.configure(text='''Developed by Gabriel Margarido - Copyright (C) 2022
Note: Please install ADB before using Snowpois0n''')

        self.menubar = tk.Menu(top,font="TkMenuFont",bg=_bgcolor,fg=_fgcolor)
        top.configure(menu = self.menubar)

        self.Label4 = tk.Label(self.top)
        self.Label4.place(relx=0.258, rely=0.917, height=21, width=364)
        self.Label4.configure(activebackground="#f9f9f9")
        self.Label4.configure(activeforeground="black")
        self.Label4.configure(anchor='w')
        self.Label4.configure(background="#d9d9d9")
        self.Label4.configure(compound='left')
        self.Label4.configure(disabledforeground="#a3a3a3")
        self.Label4.configure(font="-family {Segoe UI} -size 10")
        self.Label4.configure(foreground="#000000")
        self.Label4.configure(highlightbackground="#d9d9d9")
        self.Label4.configure(highlightcolor="black")
        self.Label4.configure(text='''Android Debug Bridge is needed to Snowpois0n works fine''')

        self.Label2_1_2 = tk.Label(self.top)
        self.Label2_1_2.place(relx=0.079, rely=0.454, height=20, width=185)
        self.Label2_1_2.configure(activebackground="#f9f9f9")
        self.Label2_1_2.configure(activeforeground="black")
        self.Label2_1_2.configure(anchor='w')
        self.Label2_1_2.configure(background="#d9d9d9")
        self.Label2_1_2.configure(compound='left')
        self.Label2_1_2.configure(disabledforeground="#a3a3a3")
        self.Label2_1_2.configure(font="-family {Segoe UI} -size 12")
        self.Label2_1_2.configure(foreground="#000000")
        self.Label2_1_2.configure(highlightbackground="#d9d9d9")
        self.Label2_1_2.configure(highlightcolor="black")
        self.Label2_1_2.configure(text='''Install iFile Root Browser''')

        self.Button1_1_1_1_1 = tk.Button(self.top)
        self.Button1_1_1_1_1.place(relx=0.029, rely=0.513, height=34, width=257)
        self.Button1_1_1_1_1.configure(activebackground="#ececec")
        self.Button1_1_1_1_1.configure(activeforeground="#000000")
        self.Button1_1_1_1_1.configure(background="#d9d9d9")
        self.Button1_1_1_1_1.configure(command=sp31_support.install_ifile)
        self.Button1_1_1_1_1.configure(compound='left')
        self.Button1_1_1_1_1.configure(disabledforeground="#a3a3a3")
        self.Button1_1_1_1_1.configure(font="-family {Segoe UI} -size 12")
        self.Button1_1_1_1_1.configure(foreground="#000000")
        self.Button1_1_1_1_1.configure(highlightbackground="#d9d9d9")
        self.Button1_1_1_1_1.configure(highlightcolor="black")
        self.Button1_1_1_1_1.configure(pady="0")
        self.Button1_1_1_1_1.configure(text='''Install iFile''')

        self.Label5 = tk.Label(self.top)
        self.Label5.place(relx=0.544, rely=0.229, height=41, width=284)
        self.Label5.configure(activebackground="#f9f9f9")
        self.Label5.configure(activeforeground="black")
        self.Label5.configure(anchor='w')
        self.Label5.configure(background="#d9d9d9")
        self.Label5.configure(compound='left')
        self.Label5.configure(disabledforeground="#a3a3a3")
        self.Label5.configure(font="-family {Segoe UI} -size 12 -weight bold")
        self.Label5.configure(foreground="#000000")
        self.Label5.configure(highlightbackground="#d9d9d9")
        self.Label5.configure(highlightcolor="black")
        self.Label5.configure(text='''Please connect your Android device
to your computer via USB cable.''')

def start_up():
    sp31_support.main()

if __name__ == '__main__':
    sp31_support.main()




